Add TF_VAR_ processes

diff --git a/.github/workflows/moon_estate_plan.yml b/.github/workflows/moon_estate_plan.yml
--- a/.github/workflows/moon_estate_plan.yml
+++ b/.github/workflows/moon_estate_plan.yml
@@ -19,7 +19,26 @@ jobs:
           role-to-assume: ${{ secrets.AWS_GITHUB_ROLE_ARN }}
           aws-region: ${{ vars.AWS_DEFAULT_REGION }}
 
-      - uses: opentofu/setup-opentofu@v1
+      - name: Load Secrets and Vars into Tofu
+        run: |
+          # Transform all Vars into TF_VAR_ lowercase
+          echo '${{ toJSON(vars) }}' | jq -r 'to_entries[] | "TF_VAR_\(.key | ascii_downcase)=\(.value)"' >> $GITHUB_ENV
+          # Transform all Secrets into TF_VAR_ lowercase
+          echo '${{ toJSON(secrets) }}' | jq -r 'to_entries[] | "TF_VAR_\(.key | ascii_downcase)=\(.value)"' >> $GITHUB_ENV
+      
+      - name: TF_VAR Guard
+        run: |
+          echo "Verifying all TF_VARs are populated..."
+          # Scan environment for TF_VARs with empty values
+          EMPTY_VARS=$(env | grep '^TF_VAR_' | awk -F= '$2=="" {print $1}')
+          
+          if [ ! -z "$EMPTY_VARS" ]; then
+            echo "ERROR: The following variables are empty in the environment:"
+            echo "$EMPTY_VARS"
+            echo "Please check your GitHub Secrets and Variables."
+            exit 1
+          fi
+          echo "All TF_VARs validated."
 
       - name: OpenTofu Init
         run: |
